name: Admin CI

on:
  pull_request:
    branches:
      - develop
    paths:
      - "packages/admin/**"
      - "packages/gap-web-ui/**"
      - ".github/workflows/admin-ci.yml"
      - "package.json"
      - "yarn.lock"

jobs:
  test:
    name: Test app

    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Generate .env files
        run: |
          cp packages/admin/.env.example packages/admin/.env
          sed -i -e '/TINYMCE_API_KEY=/s/$/${{ secrets.TINYMCE_API_KEY }}/g' packages/admin/.env

      - name: Read .nvmrc
        run: echo "::set-output name=NVMRC::$(cat .nvmrc)"
        id: nvm

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: "${{ steps.nvm.outputs.NVMRC }}"
          cache: 'yarn'

      - name: Restore next cache
        id: restore-next-cache
        uses: actions/cache/restore@v3
        with:
          path: ${{ github.workspace }}/packages/admin/.next/cache
          key: ${{ runner.os }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') }}

      - name: Install dependencies
        run: |
          yarn install --immutable
      
      - name: Lint files
        run: |
          yarn workspace admin lint

      - name: Build gap-web-ui
        run: |
          yarn workspace gap-web-ui build

      - name: Units Tests
        run: |
          yarn workspace admin coverage

      - name: Build application
        run: |
          yarn workspace admin build

      - name: Save next cache
        if: steps.restore-next-cache.outputs.cache-hit != 'true'
        uses: actions/cache/save@v3
        with:
          path: ${{ github.workspace }}/packages/admin/.next/cache
          key: ${{ runner.os }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') }}
