name: Admin CI

on:
  pull_request:
    branches:
      - develop
    paths:
      - "packages/admin/**"
      - ".github/workflows/admin-feature.yml"
      - "package.json"
      - "yarn.lock"

jobs:
  build:
    name: Test app

    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Generate .env files
        run: |
          cp packages/admin/.env.example packages/admin/.env
          sed -i -e '/TINYMCE_API_KEY=/s/$/${{ secrets.TINYMCE_API_KEY }}/g' packages/admin/.env

      - name: Read .nvmrc
        run: echo "::set-output name=NVMRC::$(cat .nvmrc)"
        id: nvm

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: "${{ steps.nvm.outputs.NVMRC }}"
          cache: 'yarn'

      - name: Install dependencies
        run: |
          yarn install --immutable

      - name: Cache gap-web-ui build
        id: cache-gap-web-ui
        uses: actions/cache@v3
        with:
          path: packages/gap-web-ui/dist
          key: ${{ runner.os }}-gap-web-ui-${{ hashFiles('packages/gap-web-ui/dist') }}

      - name: Build gap-web-ui
        if: steps.cache-gap-web-ui.outputs.cache-hit != 'true'
        run: |
          yarn workspace gap-web-ui build

      - name: Build application
        run: |
          yarn workspace admin build

      - name: Lint files
        run: |
          yarn workspace admin lint

      - name: Units Tests
        run: |
          yarn workspace admin coverage