name: Applicant Promote to Prod Workflow

on:
  push:
    branches:
      - main
    paths:
      - "packages/applicant/**"
      - "packages/gap-web-ui/**"
      - ".github/workflows/applicant-prod-cd.yml"
      - "Dockerfile"
      - "package.json"
      - "yarn.lock"

jobs:
  deploy:
    environment: AWS
    runs-on: ubuntu-latest

    permissions:
        id-token: write
        contents: read

    steps:
      - name: Setup AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          role-session-name: gap-apply-applicant-web
          aws-region: eu-west-2

      - name: Login to AWS ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Add prod tag to existing qa image
        # Based on steps described here - https://docs.aws.amazon.com/AmazonECR/latest/userguide/image-retag.html
        run: |
          MANIFEST=$(aws ecr batch-get-image --repository-name gap-apply-applicant-web --image-ids imageTag=qa --output json | jq --raw-output --join-output '.images[0].imageManifest')
          aws ecr put-image --repository-name gap-apply-applicant-web --image-tag prod --image-manifest "$MANIFEST"
