name: Applicant CI

on:
  pull_request:
    branches:
      - develop
    paths:
      - "packages/applicant/**"
      - ".github/workflows/applicant-feature.yml"
      - "package.json"
      - "yarn.lock"

jobs:
  build:
    name: Test app

    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Generate .env files
        run: |
          cp packages/applicant/.env.example packages/applicant/.env

      - name: Read .nvmrc
        run: echo "::set-output name=NVMRC::$(cat .nvmrc)"
        id: nvm

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: "${{ steps.nvm.outputs.NVMRC }}"
          cache: 'yarn'

      - name: Install dependencies
        run: |
          yarn install --immutable

      - name: Lint files
        run: |
          yarn workspace applicant lint

      - name: Download gap-web-ui
        uses: actions/download-artifact@v3
        with:
          name: gap-web-ui-dist
      
      - name: Units Tests
        run: |
          yarn workspace applicant coverage
          
      - name: Build application
        run: |
          yarn workspace applicant build