name: Applicant CI

on:
  push:
    branches:
      - feature/**
      - AFG-**
      - GAP-**
      - fix/**
      - bug/**
      - TMI2-**
    paths:
      - "packages/applicant/**"
      - ".github/workflows/**"
      - "package.json"
      - "yarn.lock"

jobs:
  build:
    name: Applicant CI

    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Generate .env files
        run: |
          cp packages/applicant/.env.example packages/applicant/.env

      - name: Read .nvmrc
        run: echo "::set-output name=NVMRC::$(cat .nvmrc)"
        id: nvm

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: "${{ steps.nvm.outputs.NVMRC }}"
          cache: 'yarn'

      - name: Install dependencies
        run: |
          yarn workspace applicant install --immutable

      - name: Snyk setup
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --yarn-workspaces --strict-out-of-sync=false

      - name: Lint files
        run: |
          yarn workspace applicant lint

      - name: Build gap-web-ui application
        run: |
          yarn workspace gap-web-ui build

      - name: Build application
        run: |
          yarn workspace applicant build

      - name: Units Tests
        run: |
          yarn workspace applicant coverage
