name: Applicant CD

on:
  push:
    branches:
      - release/**
      - develop
    paths:
      - "packages/applicant/**"
      - "packages/gap-web-ui/**"
      - ".github/workflows/applicant-pushImage.yml"
      - "package.json"
      - "yarn.lock"

env:
  AWS_REGION: eu-west-2

jobs:
  build:
      name: Test app

      runs-on: ubuntu-latest

      permissions:
        contents: read

      steps:
        - name: Checkout repo
          uses: actions/checkout@v4

        - name: Generate .env files
          run: |
            cp packages/applicant/.env.example packages/applicant/.env

        - name: Read .nvmrc
          run: echo "::set-output name=NVMRC::$(cat .nvmrc)"
          id: nvm

        - name: Setup node
          uses: actions/setup-node@v3
          with:
            node-version: "${{ steps.nvm.outputs.NVMRC }}"
            cache: 'yarn'

        - name: Install dependencies
          run: |
            yarn install --immutable

        - name: Build gap-web-ui
          run: |
            yarn workspace gap-web-ui build

        - name: Build application
          run: |
            yarn workspace applicant build

        - name: Lint files
          run: |
            yarn workspace applicant lint

        - name: Units tests
          run: |
            yarn workspace applicant coverage

        - name: Gap-web-ui units tests
          run: |
            yarn workspace gap-web-ui coverage

  imageBuild:
    needs: build

    environment: AWS
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          # Fetch all commits since we use the total commit count to determine the build version
          fetch-depth: 0

      - name: Setup AWS credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to AWS ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Determine & set BUILD_VERSION
        run: |
          GIT_COUNT=$(git rev-list $GITHUB_SHA --count)
          echo "BUILD_VERSION=b_$GIT_COUNT" >> $GITHUB_ENV
          echo BUILD_VERSION is ${{ env.BUILD_VERSION }}

      - name: Build, tag and push Docker image to AWS ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          docker build --build-arg APP_NAME=applicant -t $ECR_REGISTRY/gap-apply-applicant-web:${{ env.BUILD_VERSION }} .
          docker push $ECR_REGISTRY/gap-apply-applicant-web:${{ env.BUILD_VERSION }}

      - name: Create env tag
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          ENV_TAG=${{ (github.ref == 'refs/heads/develop' && 'develop') || (startsWith(github.ref, 'refs/heads/release') && 'qa') }}
          docker tag $ECR_REGISTRY/gap-apply-applicant-web:${{ env.BUILD_VERSION }} $ECR_REGISTRY/gap-apply-applicant-web:$ENV_TAG
          docker push $ECR_REGISTRY/gap-apply-applicant-web:$ENV_TAG

      - name: Create release tag - if we are committing to a release branch
        if: ${{ startsWith(github.ref, 'refs/heads/release/') }}
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          RELEASE_VERSION=V_${GITHUB_REF##*/}
          docker tag $ECR_REGISTRY/gap-apply-applicant-web:${{ env.BUILD_VERSION }} $ECR_REGISTRY/gap-apply-applicant-web:$RELEASE_VERSION
          docker push $ECR_REGISTRY/gap-apply-applicant-web:$RELEASE_VERSION
