name: Feature Workflow

on:
  push:
    branches:
      - feature/**
      - AFG-**
      - GAP-**
      - fix/**
      - bug/**
      - TMI2-**
    paths-ignore:
      - "*.md"

jobs:
  build:
    name: Build Feature

    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Generate .env files
        run: |
          cp packages/admin/.env.example packages/admin/.env
          sed -i -e '/TINYMCE_API_KEY=/s/$/${{ secrets.TINYMCE_API_KEY }}/g' packages/admin/.env 
          cp packages/applicant/.env.example packages/applicant/.env

      - name: Read .nvmrc
        run: echo "::set-output name=NVMRC::$(cat .nvmrc)"
        id: nvm

      - name: Setup node
        uses: actions/setup-node@3
        with:
          node-version: "${{ steps.nvm.outputs.NVMRC }}"
          cache: 'yarn'

      - name: Install dependencies
        run: |
          yarn install --frozen-lockfile

      - name: Snyk setup
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --yarn-workspaces --strict-out-of-sync=false

      - name: Lint files
        run: |
          yarn lint

      - name: Build application
        run: |
          yarn build

      - name: Units Tests
        run: |
          yarn coverage
