name: gap-web-ui CI

on:
  pull_request:
    branches:
      - develop
    paths:
      - "packages/gap-web-ui/**"
      - ".github/workflows/gap-web-ui-ci.yml"
      - "package.json"
      - "yarn.lock"

jobs:
  test:
    name: Test app

    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Read .nvmrc
        id: nvm
        run: echo "name=NVMRC::$(cat .nvmrc)" >> $GITHUB_OUTPUT

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: "${{ steps.nvm.outputs.NVMRC }}"
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --immutable

      - name: Build application
        run: yarn workspace gap-web-ui build

      - name: Units Tests
        run: yarn workspace gap-web-ui jest --ci