name: gap-web-ui CI

on:
  pull_request:
    branches:
      - develop
    paths:
      - "packages/gap-web-ui/**"
      - ".github/workflows/gap-web-ui-feature.yml"
      - "package.json"
      - "yarn.lock"

jobs:
  build:
    name: Test app

    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Read .nvmrc
        run: echo "::set-output name=NVMRC::$(cat .nvmrc)"
        id: nvm

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: "${{ steps.nvm.outputs.NVMRC }}"
          cache: 'yarn'

      - name: Install dependencies
        run: |
          yarn install --immutable

      - name: Build application
        run: |
          yarn workspace gap-web-ui build

      - name: Upload gap-web-ui-dist
        uses: actions/upload-artifact@v3
        with:
          name: gap-web-ui-dist
          path: packages/gap-web-ui/dist

      - name: Units Tests
        run: |
          yarn workspace gap-web-ui coverage